spring:
  application:
    name: ApiTaller

  datasource:
    url: jdbc:mysql://localhost:3306/apiTaller?createDatabaseIfNotExist=true
    username: harnina
    password: zzzzzz

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  api-docs:
    path: /v3/api-docs
